package ua.uz.alex.university.domain;

public enum FacultyName {
    /*  "Faculty of " */
    BIOLOGY, GEOGRAPHY, ECONOMICS, ENGINEERING, MEDICINE, DENTISTRY, HEALTHCARE, FOREIGN_PHILOLOGY, INFORMATION_TECHNOLOGIES,
    HISTORY_AND_INTERNATIONAL_RELATIONS, MATHEMATICS_AND_DIGITAL_TECHNOLOGIES, SOCIAL_SCIENCES, PHYSICS, PHILOLOGY, CHEMISTRY, LAW;
}
